# Use the official nginx image as base
FROM nginx:alpine

# Copy the HTML file to the default nginx public directory
COPY index.html /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
